preload = /home/terabit/.config/wallpapers/anime-girl-saint-bw.jpg
preload = /home/terabit/.config/wallpapers/anime-girl-saint.png
preload = /home/terabit/.config/wallpapers/rose.jpg
preload = /home/terabit/.config/wallpapers/dark_wall_angel_mb.jpg
preload = /home/terabit/.config/wallpapers/light_wall_girl.png

splash = false

wallpaper {
    monitor = eDP-1
    path = /home/terabit/.config/wallpapers/anime-girl-saint-bw.jpg
    fit_mode = cover
}
